version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongo-med
    restart: always
    ports:
      - "${MONGO_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    container_name: redis-med
    restart: always
    ports:
      - "${REDIS_ADDR}"

volumes:
  mongo-data:

#version: '3.9'
#
#services:
#  mongo:
#    image: mongo
#    container_name: mongo-med
#    restart: always
#    ports:
#      - "${MONGO_PORT}"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
#      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
#    volumes:
#      - mongo-data:/data/db
#
#volumes:
#  mongo-data: