#version: '3.8'
#
#services:
#  mongo:
#    image: mongo
#    container_name: mongo-med
#    restart: always
#    ports:
#      - "27017:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: admin
#      MONGO_INITDB_ROOT_PASSWORD: secret
#    volumes:
#      - mongo-data:/data/db
#volumes:
#  mongo-data:

version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo-med
    restart: always
    ports:
      - "${MONGO_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
